# Generated by Django 4.1.5 on 2023-02-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_swapi', '0002_swapimetadata_csv_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swapimetadata',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
